name: Docker Images Build&Push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        logout: false
          
    - name: Build Backend Docker Image
      run: docker build -t bobbun/backend:bitirme_project ./react-express-mongodb/backend

    - name: Push Backend Docker Image to Docker Hub
      run: docker push bobbun/backend:bitirme_project
      
    - name: Build Frontend Docker Image
      run: docker build -t bobbun/frontend:bitirme_project ./react-express-mongodb/frontend

    - name: Push Frontend Docker Image to Docker Hub
      run: docker push bobbun/frontend:bitirme_project

    - name: Build DB Docker Image
      run: docker build -t bobbun/backend:bitirme_project -f dockerfile.db ./react-express-mongodb

    - name: Push DB Docker Image to Docker Hub
      run: docker push bobbun/mongo:bitirme_project
